steps:
  # Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/the-gas-app-prod/scraper-images/scraper:$COMMIT_SHA', '.']
    automapSubstitutions: true
  # Push container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/the-gas-app-prod/scraper-images/scraper:$COMMIT_SHA']
    automapSubstitutions: true
  # Deploy container image to Cloud Run Jobs
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'jobs'
    - 'deploy'
    - 'scraper'
    - '--image'
    - 'us-central1-docker.pkg.dev/the-gas-app-prod/scraper-images/scraper:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--cpu'
    - '8000m'
    - '--memory'
    - '4Gi' 
    - '--parallelism'
    - '1'
    - '--set-secrets=/home/app/.ssh/id_rsa=gh-db-deploy-key:latest'
options:
  logging: CLOUD_LOGGING_ONLY
