steps:
  # Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/the-gas-app-prod/scraper-images:$COMMIT_SHA', '.']
    automapSubstitutions: true
  # Deploy container image to Cloud Run Jobs
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'jobs'
    - 'deploy'
    - 'scraper'
    - '--image'
    - 'us-central1-docker.pkg.dev/the-gas-app-prod/scraper-images:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--cpu'
    - '8000m'
    - '--memory'
    - '4Gi' 
    - '--parallelism'
    - '1'
    - '--add-volume'
    - 'type=secret,name=projects/1046315716182/secrets/gh-db-deploy-key:latest'
    - '--add-volume-mount'
    - 'volume=projects/1046315716182/secrets/gh-db-deploy-key:latest,mount-path=/home/app/.ssh'
# Images to save to Artifact Registry at build end
images:
  - 'us-central1-docker.pkg.dev/the-gas-app-prod/scraper-images:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
