name: Lint Python sources

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Local Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup pipenv
        run: python3 -m pip install pipenv

      - name: Setup flake8
        run: python3 -m pipenv install --dev --system
    
      - name: Lint with flake8
        id: flake8-lint
        run: python3 -m flake8 -v
